version: '3.8'
services:
  xlr-remote-runner:
    image: xlr-registry:5050/digitalai/xlr-remote-runner:0.1.22
    privileged: true
    user: root
    environment:
      - RELEASE_RUNNER_TOKEN=${REMOTE_RUNNER_TOKEN:?Use the access token that has been configured in Digital.ai Release.}
      - RELEASE_RUNNER_RELEASEURL=http://host.docker.internal:5516
      - SPRING_PROFILES_ACTIVE=docker
      - RELEASE_RUNNER_CAPABILITIES=remote,docker,container
    volumes:
      - ./remote-runner/db:/workspace/db
      - ./remote-runner/work:/workspace/work
      - /var/run/docker.sock:/var/run/docker.sock
