FROM xebialabsunsupported/xl-release:23.1

# Install license
# COPY default-conf/xl-release-license.lic /opt/xebialabs/xl-release-server/default-conf/

# Install plugins
COPY default-plugins /opt/xebialabs/xl-release-server/default-plugins
