version: '3.8'
services:

  digitalai-release:
    build: digitalai-release
    ports:
      - 5516:5516
    environment:
      - ADMIN_PASSWORD=admin
      - ACCEPT_EULA=Y
    user: root  # Needed for docker runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Needed for docker runner

  digitalai-release-setup:
    build: digitalai-release-setup
    depends_on:
      - digitalai-release
    command: ["apply", "-v", "-f", "/data/docker-runner.yaml"]
    volumes:
      - ./digitalai-release-setup:/data:ro

  xlr-registry:
    image: registry:2
    ports:
      - 5050:5000
    volumes:
      - .:/var/lib/registry

  xlr-registry-ui:
    image: parabuzzle/craneoperator:latest
    ports:
      - 8086:80
    environment:
      - REGISTRY_HOST=xlr-registry
      - REGISTRY_PORT=5000
      - REGISTRY_PROTOCOL=http
      - REGISTRY_ALLOW_DELETE=true
      - SSL_VERIFY=false
      - TITLE=Digital.ai Release Docker Registry
    depends_on:
      - xlr-registry
