version: '3.8'
services:

  xl-release:
    build: ./xl-release
    ports:
      - 5516:5516
    environment:
      - ADMIN_PASSWORD=admin
      - ACCEPT_EULA=Y
    user: root  # Needed for docker runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Needed for docker runner

  xlr-registry:
    image: registry:2
    ports:
      - 5050:5000
    volumes:
      - .:/var/lib/registry

  xlr-docker-registry-ui:
    image: parabuzzle/craneoperator:latest
    ports:
      - 8086:80
    environment:
      - REGISTRY_HOST=xlr-registry
      - REGISTRY_PORT=5000
      - REGISTRY_PROTOCOL=http
      - REGISTRY_ALLOW_DELETE=true
      - SSL_VERIFY=false
      - TITLE=Digital.ai Docker Registry
    depends_on:
      - xlr-registry

  xl-cli:
    build: ./xl-cli
    depends_on:
      - xl-release
    command: ["apply", "-v", "-f", "/data/docker-runner.yaml"]
    volumes:
      - ./xl-cli:/data:ro
